make it simple

diff --git a/hooks/clevis b/hooks/clevis
--- a/hooks/clevis
+++ b/hooks/clevis
@@ -21,48 +21,17 @@ EOF
             # /dev/fd missing somehow
             [ ! -d /dev/fd ] && ln -s /proc/self/fd /dev/
             echo ""
-            echo "Attempting TPM unlock on ${cryptname} volume"
-            if [ -f /etc/keyfile.jwe ]; then
-                echo "Unlocking with keyfile"
-                if clevis-decrypt-tpm2 < /etc/keyfile.jwe > /tmp/key; then
-                    if cryptsetup open ${resolved} ${cryptname} --key-file /tmp/key; then
-                        rm -f /tmp/key
-                        echo "Unlocked with keyfile"
-                        return 0
-                    else
-                        err "Cannot open LUKS volume with keyfile"
-                        return 1
-                    fi
-                else
-                    err "Cannot decrypt keyfile"
-                    return 1
-                fi
-            fi
+            echo "Attempting to unlock ${resolved} with TPM..."
 
-            if [ -f /etc/passphrase.jwe ]; then
-                echo "Unlocking with passphrase"
-                password=$(clevis-decrypt-tpm2 < /etc/passphrase.jwe)
-                if [ -n "$password" ]; then
-                    if echo "$password" | cryptsetup open ${resolved} ${cryptname}; then
-                        echo "Unlocked with passphrase"
-                        return 0
-                    else
-                        err "Cannot open LUKS volume with passphrase"
-                        return 1
-                    fi
-                else
-                    err "Cannot decrypt passphrase"
-                    return 1
-                fi
-            fi
-
-            if ! /usr/bin/clevis-luks-unlock -d ${resolved} -n ${cryptname}; then
-                err "TPM unlock failed"
+            if ! clevis-luks-unlock -d ${resolved} -n ${cryptname}; then
+                err "TPM unlock failed."
                 return 1
             fi
 
+            echo "TPM unlock succeeded."
+
             if [ ! -e "/dev/mapper/${cryptname}" ]; then
-                err "Unlock succeeded, but ${cryptname} creation failed, aborting..."
+                err "${cryptname} creation failed, aborting..."
                 return 1
             fi
         else
